# Generated by Django 2.2.16 on 2022-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220603_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
    ]
